title: Chris Pal Lab
email: group@example.edu
description: >-
  The Chris Pal Lab works on machine learning, natural language processing, computer vision, and generative modeling.
baseurl: ""
url: "https://chris-pal-group.github.io"
domain: "chris-pal-group.github.io"
lang: en
timezone: America/Toronto

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - bibtex/

header_pages:
  - news.md
  - people.md
  - publications.md

twitter_username: research_group
github_username: chris-pal-group

author:
  name: Christopher Pal

logo: /assets/images/headshots/chris_pal.jpeg

social:
  name: Chris Pal Lab
  links:
    - https://github.com/chris-pal-group
